"""User-level configuration manager for focus-prompt.

Stores API keys and model settings in ~/.config/fp/config.env
so users don't need .env files in every project directory.

Config priority (highest to lowest):
  1. Environment variables (export FP_MODEL=...)
  2. ~/.config/fp/config.env (user-level, set via `fp setup`)
  3. .env in current working directory (project-level, legacy)
"""
from __future__ import annotations

import os
from pathlib import Path


def get_config_dir() -> Path:
    """Return ~/.config/fp/ directory, creating it if needed."""
    config_dir = Path.home() / ".config" / "fp"
    config_dir.mkdir(parents=True, exist_ok=True)
    return config_dir


def get_config_path() -> Path:
    """Return path to user config file (~/.config/fp/config.env)."""
    return get_config_dir() / "config.env"


def load_user_config() -> None:
    """Load user-level config into environment (if exists).

    Does NOT override existing env vars — only fills missing ones.
    This preserves the priority: env var > user config > CWD .env
    """
    config_path = get_config_path()
    if config_path.exists():
        _load_env_file(config_path, override=False)


def _load_env_file(path: Path, override: bool = False) -> None:
    """Load a .env file into os.environ.

    Handles comments, blank lines, and quoted values.
    Does not override existing env vars unless override=True.
    """
    if not path.exists():
        return

    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" not in line:
                continue

            key, _, value = line.partition("=")
            key = key.strip()
            value = value.strip()

            # Remove surrounding quotes
            if len(value) >= 2 and value[0] == value[-1] and value[0] in ('"', "'"):
                value = value[1:-1]

            if override or not os.getenv(key):
                os.environ[key] = value


def save_user_config(settings: dict[str, str]) -> Path:
    """Save settings to ~/.config/fp/config.env.

    Merges with existing config — only overwrites specified keys.
    Comments and other keys are preserved.

    Args:
        settings: Dict of KEY=value pairs to save.

    Returns:
        Path to the config file.
    """
    config_path = get_config_path()
    existing: dict[str, str] = {}

    # Read existing config
    if config_path.exists():
        with open(config_path) as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                if "=" in line:
                    key, _, value = line.partition("=")
                    existing[key.strip()] = value.strip()

    # Merge
    existing.update(settings)

    # Write back
    lines = [
        "# focus-prompt user config",
        "# Generated by `fp setup` — edit manually or re-run `fp setup`",
        "",
    ]

    # Group by category
    model_keys = ["FP_MODEL"]
    key_keys = [k for k in existing if k.endswith("_API_KEY")]
    base_keys = [k for k in existing if k.endswith("_API_BASE")]
    other_keys = [k for k in existing if k not in model_keys + key_keys + base_keys]

    if any(k in existing for k in model_keys):
        lines.append("# ─── Model ────────────────────────────────────")
        for k in model_keys:
            if k in existing:
                lines.append(f"{k}={existing[k]}")
        lines.append("")

    if key_keys:
        lines.append("# ─── API Keys ────────────────────────────────")
        for k in sorted(key_keys):
            lines.append(f"{k}={existing[k]}")
        lines.append("")

    if base_keys:
        lines.append("# ─── Custom Endpoints (optional) ──────────────")
        for k in sorted(base_keys):
            lines.append(f"{k}={existing[k]}")
        lines.append("")

    if other_keys:
        lines.append("# ─── Other ───────────────────────────────────")
        for k in sorted(other_keys):
            lines.append(f"{k}={existing[k]}")
        lines.append("")

    config_path.write_text("\n".join(lines) + "\n")
    return config_path


def get_current_config() -> dict[str, str]:
    """Return current config values (from env or file).

    Shows what's currently active, regardless of source.
    """
    keys = [
        "FP_MODEL",
        "OPENAI_API_KEY",
        "MINIMAX_API_KEY",
        "MINIMAX_API_BASE",
        "DEEPSEEK_API_KEY",
        "DASHSCOPE_API_KEY",
        "ZAI_API_KEY",
        "MOONSHOT_API_KEY",
        "VOLCENGINE_API_KEY",
        "TENCENT_API_KEY",
        "XIAOMI_MIMO_API_KEY",
        "XIAOMI_MIMO_API_BASE",
        "EXA_API_KEY",
    ]
    return {k: os.getenv(k, "") for k in keys}
